"""
Weekly Portfolio RL Training (Leak-Safe)
=======================================

This module provides a baseline reinforcement‑learning setup for weekly
portfolio rebalancing using only technical indicators as inputs.  It
implements two candidate algorithms—PPO and SAC—from the
stable‑baselines3 library.  The environment maps continuous actions to
long‑only portfolio weights via a softmax, and the reward is a
Sharpe‑like measure calculated from an exponentially weighted moving
variance of portfolio returns.  Early stopping is used to halt
training when the validation Sharpe no longer improves.

Key Features:
* **Gymnasium** is used instead of the deprecated gym library.
* **No type annotations** are included to avoid distractions.
* **No argparse** is used; instead, a `run()` function exposes the
  training interface for notebook or script use.
* **Finite action bounds** ensure compatibility with stable‑baselines3.
* **Technical features only**: macro data is ignored; feature names
  come from `metadata.json`.
* **Early stopping** monitors validation Sharpe at regular intervals.
* **Softmax temperature** allows control over weight sharpness.

To use this module interactively in a notebook:

```python
import train_rl_weekly as trw
trw.run(data_dir="data", algo="ppo", total_steps=300000)
```

Ensure your `data/` folder contains the preprocessed splits
(`train/technical.csv`, `train/log_returns.csv`, etc.) and a
corresponding `metadata.json` generated by your data preparation
pipeline.
"""

import os
import json
import math
from pathlib import Path

import numpy as np
import pandas as pd

# Try to import gymnasium; fall back to gym if gymnasium is not installed.  Stable-baselines3
# works with either.  This allows the script to run in environments where only gym is
# available or where gymnasium is installed.
try:
    import gymnasium as gym  # type: ignore
    from gymnasium import spaces  # type: ignore
except ImportError:
    import gym  # type: ignore
    from gym import spaces  # type: ignore

import torch as th
from stable_baselines3 import PPO, SAC
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.callbacks import BaseCallback

# =========================
# User‑tweakable defaults
# =========================

# Directory where the data and metadata are stored
DATA_DIR = "data"

# Algorithm to use: "ppo" or "sac"
ALGO = "ppo"

# Total number of environment steps to train
TOTAL_STEPS = 100_000

# Frequency (in steps) at which to evaluate the model on the
# validation set.  A larger value reduces validation overhead.
EVAL_FREQ = 10_000

# Number of evaluation rounds with no improvement before stopping
PATIENCE = 10

# EMA window (in weeks) used to compute the running volatility for the
# Sharpe‑like reward.  Typical values range from 12 to 26.
ROLLING_VOL_W = 12

# Learning rate for the optimizer
LEARNING_RATE = 3e-4

# Discount factor (gamma) for RL algorithms
GAMMA = 0.98

# Random seed for reproducibility
SEED = 42

# Softmax temperature: actions are scaled by this factor before
# softmax.  Higher values produce more concentrated weights.
SOFTMAX_TEMPERATURE = 6.0


# -----------------------------
# Data loading utilities
# -----------------------------

def load_metadata(data_dir):
    """Load metadata from a JSON file in the specified directory."""
    path = Path(data_dir) / "metadata.json"
    with open(path, "r") as f:
        return json.load(f)


def load_split_frames(data_dir, split, meta):
    """
    Load the normalized technical features and log returns for a given
    split ("train", "val", or "test").

    Parameters
    ----------
    data_dir : str or Path
        Base directory containing the data splits and metadata.
    split : str
        One of "train", "val", or "test".
    meta : dict
        Metadata dictionary loaded from metadata.json.

    Returns
    -------
    tech_df : pandas.DataFrame
        Long‑format normalized technical features with columns
        containing the features and a 'ticker' column.
    logret_wide : pandas.DataFrame
        Wide matrix of weekly log returns (index: date, columns:
        tickers).  This matrix is split‑scoped to avoid leakage.
    tickers : list of str
        Ordered list of tickers present in both technical and return
        data.  All processing will use this ordering.
    feat_cols : list of str
        Technical feature column names to feed into the model.  These
        correspond to the columns normalized during data preparation.
    """
    data_dir = Path(data_dir)

    # Load technical features
    tech_path = data_dir / split / "technical.csv"
    tech_df = pd.read_csv(tech_path, index_col=0, parse_dates=True)
    if "ticker" not in tech_df.columns:
        raise ValueError(f"{split}/technical.csv must contain a 'ticker' column.")

    # Select only the feature columns that were normalized
    feat_cols = meta.get("normalization", {}).get("technical", {}).get("columns", [])
    feat_cols = [c for c in feat_cols if c in tech_df.columns]

    # Load log returns (wide matrix) for this split
    ret_path = data_dir / split / "log_returns.csv"
    logret_wide = pd.read_csv(ret_path, index_col=0, parse_dates=True).sort_index()

    # Determine tickers that appear in both technical and return data
    tickers_feat = sorted(tech_df["ticker"].unique().tolist())
    tickers_ret = sorted(logret_wide.columns.tolist())
    tickers = [t for t in tickers_feat if t in tickers_ret]
    if not tickers:
        raise ValueError("No overlapping tickers between features and returns.")

    # Align both datasets to the intersection of dates
    common_idx = tech_df.index.intersection(logret_wide.index)
    tech_df = tech_df.loc[common_idx]
    logret_wide = logret_wide.loc[common_idx, tickers]

    return tech_df, logret_wide, tickers, feat_cols


def feature_matrix_on_date(date, tech_df, tickers, feat_cols):
    """
    Build a matrix of shape (n_assets, n_features) for a single date.

    This function extracts the rows corresponding to the given date from
    the technical features DataFrame, pivots them into a matrix
    indexed by ticker, and returns the feature values in the order
    specified by the 'tickers' list.  Missing values are filled with
    zero to ensure a well‑formed input matrix.

    Parameters
    ----------
    date : pandas.Timestamp
        The date for which to extract the feature matrix.
    tech_df : pandas.DataFrame
        Long‑format DataFrame of technical features.
    tickers : list of str
        Ordered list of tickers.
    feat_cols : list of str
        List of feature column names to include.

    Returns
    -------
    np.ndarray
        A 2D array of shape (n_assets, n_features) containing the
        feature values.  Any NaNs are replaced with zero.
    """
    rows = tech_df.loc[[date]]
    mat = (
        rows.set_index("ticker")[feat_cols]
        .reindex(tickers)
        .astype(np.float32)
        .fillna(0.0)
        .values
    )
    return mat


# ---------------------------------
# Portfolio Environment (weekly)
# ---------------------------------

class WeeklyPortfolioEnv(gym.Env):
    """
    A reinforcement learning environment for weekly portfolio rebalancing.

    Observations consist of the concatenated technical features for all
    tickers at the current week.  Actions are vectors in a bounded
    continuous space; these are scaled and passed through a softmax to
    produce portfolio weights that lie on the simplex (long‑only and
    fully invested).  The reward for each step is a Sharpe‑like
    quantity: the next week's portfolio log return divided by a
    running volatility estimate, annualized via sqrt(52).  The
    volatility estimate is an exponentially weighted moving variance of
    past portfolio returns.

    Parameters
    ----------
    tech_df : pandas.DataFrame
        Long‑format DataFrame of normalized technical features (by date
        and ticker).
    logret_wide : pandas.DataFrame
        Wide DataFrame of weekly log returns (columns: tickers).
    tickers : list of str
        Ordered list of tickers for the environment.
    feat_cols : list of str
        List of feature column names used in the observation.
    rolling_vol_window : int, optional
        Window length (in weeks) for the volatility EMA.  A minimum of
        this many timesteps will be consumed before starting the
        environment.  Default is 12.
    vol_ema_alpha : float or None, optional
        If specified, this directly sets the smoothing factor for the
        EMA variance.  Otherwise, alpha = 2/(window+1).  Default is
        None.
    random_start : bool, optional
        If True, each episode will start at a random time index within
        the available dates (after the warmup period).  Otherwise, the
        episode starts at the earliest valid index.  Default is
        False.
    softmax_temperature : float, optional
        Scale factor applied to actions before the softmax operation.
        Larger values lead to more peaked (less uniform) weight
        distributions.  Default is SOFTMAX_TEMPERATURE.
    """

    metadata = {"render_modes": []}

    def __init__(
        self,
        tech_df,
        logret_wide,
        tickers,
        feat_cols,
        rolling_vol_window=12,
        vol_ema_alpha=None,
        random_start=False,
        softmax_temperature=SOFTMAX_TEMPERATURE,
    ):
        super().__init__()
        self.tech_df = tech_df
        self.logret_wide = logret_wide
        self.tickers = tickers
        self.feat_cols = feat_cols
        self.n_assets = len(tickers)
        self.n_features = len(feat_cols)
        self.random_start = random_start
        self.temperature = float(softmax_temperature)

        # Finite action space required by stable‑baselines3.  We use
        # [-1, 1] bounds, then scale by temperature and apply softmax.
        self.action_space = spaces.Box(
            low=-1.0,
            high=1.0,
            shape=(self.n_assets,),
            dtype=np.float32,
        )

        # Observation is a flat vector of features for all assets
        self.observation_space = spaces.Box(
            low=-np.inf,
            high=np.inf,
            shape=(self.n_assets * self.n_features,),
            dtype=np.float32,
        )

        # Date index for the environment
        self.dates = self.logret_wide.index.sort_values()

        # Rolling window for volatility estimate
        self.W = int(rolling_vol_window)
        self.alpha = float(vol_ema_alpha) if vol_ema_alpha is not None else (2.0 / (self.W + 1.0))

        # The earliest index from which we can start (need W steps for
        # the volatility warmup) and at least one future return
        self.start_idx = max(self.W, 1)

        # Internal state variables
        self._t = None
        self._weights = None
        self._ema_mean = 0.0
        self._ema_var = 0.0
        self._ema_initialized = False

    def _get_obs(self):
        """Return the current observation as a flat vector."""
        d = self.dates[self._t]
        X = feature_matrix_on_date(d, self.tech_df, self.tickers, self.feat_cols)
        return X.flatten()

    def _softmax(self, x):
        """
        Convert action vector to portfolio weights using softmax.
        A temperature scale is applied prior to softmax to control
        sharpness of the resulting distribution.
        """
        x = np.asarray(x, dtype=np.float32) * self.temperature
        x = x - np.max(x)  # numerical stability
        e = np.exp(x)
        return e / (e.sum() + 1e-12)

    def reset(self, seed=None, options=None):
        """Reset the environment state at the start of an episode."""
        super().reset(seed=seed)
        if self.random_start:
            # Choose a random starting index within the valid range
            self._t = np.random.randint(self.start_idx, len(self.dates) - 2)
        else:
            # Deterministic start at earliest valid index
            self._t = self.start_idx

        # Initialize with equal weights
        self._weights = np.ones(self.n_assets, dtype=np.float32) / self.n_assets
        self._ema_mean = 0.0
        self._ema_var = 0.0
        self._ema_initialized = False

        return self._get_obs(), {}

    def step(self, action):
        """
        Execute one rebalancing action and observe the reward.
        """
        # Convert unbounded action to portfolio weights
        action = np.asarray(action, dtype=np.float32).reshape(-1)
        w = self._softmax(action)
        self._weights = w

        # Check if a future return exists
        if self._t + 1 >= len(self.dates) - 1:
            return self._get_obs(), 0.0, True, False, {}

        next_date = self.dates[self._t + 1]
        r_vec = self.logret_wide.loc[next_date, self.tickers].values.astype(np.float32)
        port_log_r = float(np.dot(w, r_vec))

        # Update EMA of mean and variance of returns
        if not self._ema_initialized:
            self._ema_mean = port_log_r
            self._ema_var = 0.0
            self._ema_initialized = True
        else:
            delta = port_log_r - self._ema_mean
            self._ema_mean += self.alpha * delta
            self._ema_var = (1.0 - self.alpha) * (self._ema_var + self.alpha * delta * delta)

        running_vol = math.sqrt(max(self._ema_var, 1e-12))
        reward = (port_log_r / (running_vol + 1e-12)) * math.sqrt(52.0)

        # Advance time index
        self._t += 1
        terminated = self._t >= (len(self.dates) - 2)
        info = {"port_log_r": port_log_r, "running_vol": running_vol}
        return self._get_obs(), float(reward), terminated, False, info

    def run_full_pass(self, model):
        """
        Run an entire episode with the given model and return the
        out‑of‑sample Sharpe ratio (annualized).
        """
        obs, _ = self.reset()
        rets = []
        done = False
        while not done:
            action, _ = model.predict(obs, deterministic=True)
            obs, _, done, _, info = self.step(action)
            if "port_log_r" in info:
                rets.append(info["port_log_r"])
        rets = np.asarray(rets, dtype=np.float64)
        if rets.std() < 1e-12:
            return 0.0
        return float((rets.mean() / (rets.std() + 1e-12)) * math.sqrt(52.0))


# ---------------------------------
# Early stopping on validation
# ---------------------------------

class ValSharpeEarlyStop(BaseCallback):
    """
    Callback to perform early stopping based on validation Sharpe.

    At regular intervals defined by `eval_freq` environment steps, the
    model is evaluated on a separate validation environment.  If the
    best validation Sharpe does not improve for `patience` evaluations
    in a row, training is halted.  When an improvement is observed,
    the model is saved to `best_model_path` (if provided).
    """

    def __init__(self, val_env, eval_freq=10_000, patience=5, best_model_path=None, verbose=1):
        super().__init__(verbose)
        self.val_env = val_env
        self.eval_freq = int(eval_freq)
        self.patience = int(patience)
        self.best_model_path = Path(best_model_path) if best_model_path else None
        self.best_sharpe = -np.inf
        self.no_improve = 0

    def _on_step(self):
        # Only evaluate at specified intervals
        if self.eval_freq <= 0 or (self.n_calls % self.eval_freq) != 0:
            return True

        sharpe = self.val_env.run_full_pass(self.model)
        if self.verbose:
            print(f"[Eval] steps={self.num_timesteps:,}  val_sharpe={sharpe:.3f}  best={self.best_sharpe:.3f}")

        # Check for improvement
        if sharpe > self.best_sharpe + 1e-6:
            self.best_sharpe = sharpe
            self.no_improve = 0
            if self.best_model_path is not None:
                self.model.save(str(self.best_model_path))
                if self.verbose:
                    print(f"  ✓ New best saved -> {self.best_model_path}")
        else:
            self.no_improve += 1
            if self.no_improve >= self.patience:
                if self.verbose:
                    print(f"  ⛔ Early stopping (no improvement in {self.patience} evals).")
                return False
        return True


# ---------------------------------
# Training and evaluation pipeline
# ---------------------------------

def train_and_select(
    data_dir=DATA_DIR,
    algo=ALGO,
    total_steps=TOTAL_STEPS,
    eval_freq=EVAL_FREQ,
    patience=PATIENCE,
    rolling_vol_window=ROLLING_VOL_W,
    learning_rate=LEARNING_RATE,
    gamma=GAMMA,
    seed=SEED,
):
    """
    Train a reinforcement learning agent on the given data and return
    performance metrics.

    Parameters
    ----------
    data_dir : str or Path, optional
        Directory containing the processed data and metadata.  Defaults
        to the module constant DATA_DIR.
    algo : str, optional
        Which algorithm to use ("ppo" or "sac").  Defaults to
        ALGO.
    total_steps : int, optional
        Total number of training steps.  Defaults to TOTAL_STEPS.
    eval_freq : int, optional
        Number of steps between validation evaluations.  Defaults
        to EVAL_FREQ.
    patience : int, optional
        Number of evaluations with no improvement before stopping.
        Defaults to PATIENCE.
    rolling_vol_window : int, optional
        EMA window for volatility in the reward.  Defaults to
        ROLLING_VOL_W.
    learning_rate : float, optional
        Learning rate for the optimizer.  Defaults to
        LEARNING_RATE.
    gamma : float, optional
        Discount factor.  Defaults to GAMMA.
    seed : int, optional
        Random seed.  Defaults to SEED.

    Returns
    -------
    dict
        A dictionary containing the train, validation, and test Sharpe
        ratios and the path to the saved model.
    """
    # Set seeds for reproducibility
    th.manual_seed(seed)
    np.random.seed(seed)

    meta = load_metadata(data_dir)

    # Load splits
    tech_tr, ret_tr, tickers, feat_cols = load_split_frames(data_dir, "train", meta)
    tech_va, ret_va, _, _ = load_split_frames(data_dir, "val", meta)
    tech_te, ret_te, _, _ = load_split_frames(data_dir, "test", meta)

    # Create environments
    env_tr = WeeklyPortfolioEnv(
        tech_tr,
        ret_tr,
        tickers,
        feat_cols,
        rolling_vol_window=rolling_vol_window,
        softmax_temperature=SOFTMAX_TEMPERATURE,
    )
    env_va = WeeklyPortfolioEnv(
        tech_va,
        ret_va,
        tickers,
        feat_cols,
        rolling_vol_window=rolling_vol_window,
        softmax_temperature=SOFTMAX_TEMPERATURE,
    )
    env_te = WeeklyPortfolioEnv(
        tech_te,
        ret_te,
        tickers,
        feat_cols,
        rolling_vol_window=rolling_vol_window,
        softmax_temperature=SOFTMAX_TEMPERATURE,
    )

    vec_env = DummyVecEnv([lambda: env_tr])

    algo = str(algo).lower()
    if algo == "ppo":
        # Choose a batch_size that divides n_steps (2048) to avoid warnings
        model = PPO(
            "MlpPolicy",
            vec_env,
            learning_rate=learning_rate,
            gamma=gamma,
            seed=seed,
            verbose=1,
            policy_kwargs=dict(activation_fn=th.nn.ReLU, net_arch=[256, 256]),
            batch_size=512,
            n_steps=2048,
            gae_lambda=0.95,
            ent_coef=0.1,
            clip_range=0.2,
        )
    elif algo == "sac":
        model = SAC(
            "MlpPolicy",
            vec_env,
            learning_rate=learning_rate,
            gamma=gamma,
            seed=seed,
            verbose=1,
            policy_kwargs=dict(
                activation_fn=th.nn.ReLU,
                net_arch=dict(pi=[256, 256], qf=[256, 256])
            ),
            buffer_size=200_000,
            batch_size=1024,
            tau=0.02,
            train_freq=64,
            gradient_steps=64,
        )
    else:
        raise ValueError("algo must be 'ppo' or 'sac'")

    # Set up early stopping callback
    best_model_path = Path(data_dir) / f"best_{algo}.zip"
    cb = ValSharpeEarlyStop(
        val_env=env_va,
        eval_freq=eval_freq,
        patience=patience,
        best_model_path=best_model_path,
        verbose=1,
    )

    # Train
    model.learn(total_timesteps=int(total_steps), callback=cb)

    # Load best model if it was saved
    if best_model_path.exists():
        model = (PPO if algo == "ppo" else SAC).load(str(best_model_path), env=vec_env)

    # Evaluate
    tr_sh = env_tr.run_full_pass(model)
    va_sh = env_va.run_full_pass(model)
    te_sh = env_te.run_full_pass(model)

    print("\n=== Final Sharpe (annualized) ===")
    print(f"Train: {tr_sh:.3f}")
    print(f"Valid: {va_sh:.3f}")
    print(f" Test: {te_sh:.3f}")

    final_path = Path(data_dir) / f"final_{algo}.zip"
    model.save(str(final_path))
    print(f"\nSaved final model -> {final_path}")

    return {"train_sharpe": tr_sh, "val_sharpe": va_sh, "test_sharpe": te_sh, "path": str(final_path)}


# -----------------------------
# Friendly entry point
# -----------------------------

def run(
    data_dir=DATA_DIR,
    algo=ALGO,
    total_steps=TOTAL_STEPS,
    eval_freq=EVAL_FREQ,
    patience=PATIENCE,
    rolling_vol_window=ROLLING_VOL_W,
    learning_rate=LEARNING_RATE,
    gamma=GAMMA,
    seed=SEED,
):
    """
    Run the training pipeline with the specified parameters.  This
    function is designed for interactive use in notebooks or scripts.

    Examples
    --------

    >>> import train_rl_weekly as trw
    >>> trw.run(data_dir="data", algo="ppo", total_steps=200_000)

    Parameters
    ----------
    data_dir : str or Path
        Base directory containing the processed data.
    algo : str
        "ppo" or "sac".
    total_steps : int
        Number of environment steps to train.
    eval_freq : int
        Evaluation frequency on the validation set.
    patience : int
        Number of evaluations without improvement before stopping.
    rolling_vol_window : int
        EMA window for volatility estimation.
    learning_rate : float
        Learning rate for the optimizer.
    gamma : float
        Discount factor.
    seed : int
        Random seed for reproducibility.

    Returns
    -------
    dict
        Dictionary containing train, validation, and test Sharpe
        ratios and the path to the saved model.
    """
    return train_and_select(
        data_dir=data_dir,
        algo=algo,
        total_steps=total_steps,
        eval_freq=eval_freq,
        patience=patience,
        rolling_vol_window=rolling_vol_window,
        learning_rate=learning_rate,
        gamma=gamma,
        seed=seed,
    )


if __name__ == "__main__":
    # When run as a script, execute the training with default
    # parameters.  Users can modify the constants at the top of the
    # file to suit their needs.
    run()